-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.boards
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    "backgroundImage" character varying(255),
    users_id integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cards
(
    id integer NOT NULL,
    "order" integer NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255),
    due_date timestamp with time zone,
    users_id integer NOT NULL,
    lists_id integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.comments
(
    id integer NOT NULL,
    "order" integer NOT NULL,
    content character varying(255) NOT NULL,
    users_id integer NOT NULL,
    cards_id integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.lists
(
    id integer NOT NULL,
    "order" integer NOT NULL,
    title character varying(255) NOT NULL,
    users_id integer NOT NULL,
    boards_id integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    "firstName" character varying(255) NOT NULL,
    "lastName" character varying(255) NOT NULL,
    "profilePhoto" character varying(255),
    password character varying(255),
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.boards
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cards
    ADD FOREIGN KEY (lists_id)
    REFERENCES public.lists (id)
    NOT VALID;


ALTER TABLE public.cards
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.comments
    ADD FOREIGN KEY (cards_id)
    REFERENCES public.cards (id)
    NOT VALID;


ALTER TABLE public.comments
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.lists
    ADD FOREIGN KEY (boards_id)
    REFERENCES public.boards (id)
    NOT VALID;


ALTER TABLE public.lists
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id)
    NOT VALID;

END;